replicaCount: 2

image:
  repository: bom.ocir.io/bmzbbujw9kal/dev-repo-test/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  NODE_ENV: production
  PORT: "3000"
  LOG_LEVEL: info

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

healthCheck:
  path: /health
  port: 3000

ingress:
  enabled: false
  host: ""
  path: /
