apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: build-agent
    app.kubernetes.io/managed-by: jenkins
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    - name: node
      image: node:20-alpine
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: '2'
          memory: 2Gi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: '2'
          memory: 4Gi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
        - name: docker-config
          mountPath: /kaniko/.docker
          readOnly: true

    - name: trivy
      image: aquasec/trivy:latest
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: '1'
          memory: 2Gi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
        - name: trivy-cache
          mountPath: /root/.cache/trivy

    - name: gitleaks
      image: zricethezav/gitleaks:latest
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: helm
      image: alpine/helm:latest
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: kubectl
      image: bitnami/kubectl:latest
      command: ['sleep']
      args: ['infinity']
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

  volumes:
    - name: workspace
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: ocir-docker-config
        optional: true
    - name: trivy-cache
      emptyDir: {}
